=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo/ConfigurationInfo.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ROOT">
	<xs:complexType>
  	<xs:sequence>
		<xs:element name="CONFIGURATION">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="VIEW" minOccurs="1" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
				<xs:element name="COLUMN" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="Type"	     type="xs:string" />
					<xs:attribute name="Name"	     type="xs:string" />
					<xs:attribute name="StorageName" type="xs:string" />
					<xs:attribute name="DataType"	 type="xs:string" />
					<xs:attribute name="DataChoices" type="xs:string" />
				</xs:complexType>
				</xs:element>
				</xs:sequence>
				<xs:attribute name="Name" 			type="xs:string"/>
				<xs:attribute name="Type" 			type="xs:string"/>
				<xs:attribute name="Description" 	type="xs:string"/>
			</xs:complexType>
			</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" 			type="xs:string"/>
		</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:schema>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo/DQMHistosConsumerConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="DQMHistosConsumerConfiguration">
			<VIEW Name="DQM_HISTOS_CONSUMER_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="ProcessorID" 	 StorageName="PROCESSOR_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="YesNo" 	 Name="SaveDQMFile" 	 StorageName="SAVE_DQM_FILE" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="DQMFilePath" 	 StorageName="DQM_FILE_PATH" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="DQMFileNamePrefix" 	 StorageName="DQM_FILE_NAME_PREFIX" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo/DataManagerConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="DataManagerConfiguration">
			<VIEW Name="DATA_MANAGER_CONFIGURATION" Type="File,Database,DatabaseTest">
				<COLUMN Type="GroupID-0" 	 Name="DataManagerGroupID" 	 StorageName="DATA_MANAGER_GROUP_ID" 		DataType="VARCHAR2"/>
				<COLUMN Type="UID" 	 Name="DataBufferUID" 	 StorageName="DATA_BUFFER_UID" 		DataType="VARCHAR2"/>
				<COLUMN Type="ChildLink-0" 	 Name="LinkToDataBufferConfiguration" 	 StorageName="LINK_TO_DATA_BUFFER_CONFIGURATION" 		DataType="VARCHAR2"/>
				<COLUMN Type="ChildLinkGroupID-0" 	 Name="LinkToDataBufferGroupID" 	 StorageName="LINK_TO_DATA_BUFFER_GROUP_ID" 		DataType="VARCHAR2"/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2"/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2"/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2"/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE"/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/VersionAliasesConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="VersionAliasesConfiguration">
			<VIEW Name="VERSION_ALIASES_CONFIGURATION" Type="File,Database,DatabaseTest">
				<COLUMN Type="UID" 	 Name="VersionAliasUID" 	 StorageName="VERSION_ALIAS_UID" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="ConfigurationName" 	 StorageName="CONFIGURATION_NAME" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="VersionAlias" 	 StorageName="VERSION_ALIAS" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="Version" 	 StorageName="VERSION" 		DataType="VARCHAR2"/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2"/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2"/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE"/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo/IterationCommandExecuteMacroConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="IterationCommandExecuteMacroConfiguration">
			<VIEW Name="ITERATION_COMMAND_EXECUTE_MACRO_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="CommandID" 	 StorageName="COMMAND_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLink-targets" 	 Name="LinkToTargets" 	 StorageName="LINK_TO_TARGETS" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,IterationTargetConfiguration"/>
				<COLUMN Type="ChildLinkGroupID-targets" 	 Name="LinkToTargetsGroupID" 	 StorageName="LINK_TO_TARGETS_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="MacroName" 	 StorageName="MACRO_NAME" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLink-macroParameters" 	 Name="LinkToMacroParameterGroup" 	 StorageName="LINK_TO_MACRO_PARAMETER_GROUP" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLinkGroupID-macroParameters" 	 Name="LinkToMacroParameterGroupID" 	 StorageName="LINK_TO_MACRO_PARAMETER_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo/Mu2eGlobalsConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="Mu2eGlobalsConfiguration">
			<VIEW Name="MU2E_GLOBALS_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="NumberOfLoopbacks" 	 StorageName="NUMBER_OF_LOOPBACKS" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="NumberOfCAPTANPulses" 	 StorageName="NUMBER_OF_CAPTAN_PULSES" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/XDAQApplicationPropertyConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="XDAQApplicationPropertyConfiguration">
			<VIEW Name="XDAQ_APPLICATION_PROPERTY_CONFIGURATION" Type="File,Database,DatabaseTest" Description="Properties%20entered%20in%20this%20table%20will%20be%20included%20in%20the%20xdaq%20configuration%20file%20as%20an%20XML%20property%20tag.%0A%0AThere%20is%20one%20exception%20to%20this%20rule%2C%20if%20PropertyType%20is%20'ots-only%20Property'%20then%20it%20will%20be%20omitted%20from%20the%20xdaq%20configuration%20file%2C%20and%20will%20be%20used%20within%20the%20otsdaq%20Supervisor%20class%20as%20a%20Supervisor%20property.%20Known%20such%20ots-only%20properties%20are%20listed%20as%20fixed%20choice%20options%20within%20the%20PropertyName%20field.">
				<COLUMN Type="GroupID-PropertyGroup" 	 Name="PropertyGroupID" 	 StorageName="PROPERTY_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="PropertyName" 	 StorageName="PROPERTY_NAME" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,UserPermissionsThreshold,UserGroupsAllowed,UserGroupsDisallowed,RequireUserLockRequestTypes,CheckUserLockRequestTypes,AutomatedRequestTypes,AllowNoLoginRequestTypes"/>
				<COLUMN Type="FixedChoiceData" 	 Name="PropertyType" 	 StorageName="PROPERTY_TYPE" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,xsd%3Astring,xsd%3Ainteger,xsd%3AunsignedInt,xsd%3Aboolean,xsd%3AunsignedShort,ots%3A%3ASupervisorProperty"/>
				<COLUMN Type="Data" 	 Name="PropertyValue" 	 StorageName="PROPERTY_VALUE" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/IterationCommandConfigureAliasConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="IterationCommandConfigureAliasConfiguration">
			<VIEW Name="ITERATION_COMMAND_CONFIGURE_ALIAS_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="CommandID" 	 StorageName="COMMAND_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="SystemAlias" 	 StorageName="SYSTEM_ALIAS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/DesktopWindowParameterConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="DesktopWindowParameterConfiguration">
			<VIEW Name="DESKTOP_WINDOW_PARAMETER_CONFIGURATION" Type="File,Database,DatabaseTest" Description="The%20parameters%20in%20this%20table%20are%20linked%20to%20by%20the%20DesktopIconConfiguration%20table%2C%20and%20they%20become%20GET%20parameters%20for%20the%20target%20window.%0A%0AThe%20GET%20parameters%20can%20then%20be%20used%20by%20the%20window's%20source%20code%20(i.e.%20HTML%20and%20JavaScript)%20to%20affect%20the%20presentation%20of%20the%20window's%20content.">
				<COLUMN Type="GroupID-windowParameters" 	 Name="windowParameterGroupID" 	 StorageName="WINDOW_PARAMETER_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="windowParameterUID" 	 StorageName="WINDOW_PARAMETER_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="Enabled" 	 StorageName="ENABLED" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="windowParameterKey" 	 StorageName="WINDOW_PARAMETER_KEY" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="windowParameterValue" 	 StorageName="WINDOW_PARAMETER_VALUE" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>
