=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo/ConfigurationInfo.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ROOT">
	<xs:complexType>
  	<xs:sequence>
		<xs:element name="CONFIGURATION">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="VIEW" minOccurs="1" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
				<xs:element name="COLUMN" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="Type"	     type="xs:string" />
					<xs:attribute name="Name"	     type="xs:string" />
					<xs:attribute name="StorageName" type="xs:string" />
					<xs:attribute name="DataType"	 type="xs:string" />
					<xs:attribute name="DataChoices" type="xs:string" />
				</xs:complexType>
				</xs:element>
				</xs:sequence>
				<xs:attribute name="Name" 			type="xs:string"/>
				<xs:attribute name="Type" 			type="xs:string"/>
				<xs:attribute name="Description" 	type="xs:string"/>
			</xs:complexType>
			</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" 			type="xs:string"/>
		</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:schema>

=== Mu2e/otsdaq_mu2e/Data/ConfigurationInfo/UDPDataListenerProducerConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="UDPDataListenerProducerConfiguration">
			<VIEW Name="UDP_DATA_LISTENER_PRODUCER_CONFIGURATION" Type="File,Database,DatabaseTest">
				<COLUMN Type="UID" 	 Name="ProcessorUID" 	 StorageName="PROCESSOR_UID" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="BufferSize" 	 StorageName="BUFFER_SIZE" 		DataType="NUMBER"/>
				<COLUMN Type="Data" 	 Name="HostIPAddress" 	 StorageName="HOST_IP_ADDRESS" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="HostPort" 	 StorageName="HOST_PORT" 		DataType="NUMBER"/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2"/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2"/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE"/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/DataBufferConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="DataBufferConfiguration">
			<VIEW Name="DATA_BUFFER_CONFIGURATION" Type="File,Database,DatabaseTest" Description="This%20table%20is%20used%20to%20associate%20Data%20Processors%20with%20Data%20Buffers.%20Each%20Data%20Buffer%20Group%20can%20have%20one%20or%20many%20Data%20Processors.%20Data%20Processors%20can%20be%20of%20type%20Producer%20(writes%20to%20a%20Data%20Buffer)%20or%20Consumer%20(reads%20from%20a%20Data%20Buffer).%20%0A%0AThis%20tables%20also%20is%20used%20to%20associate%20a%20Data%20Processor%20plug-in%20class%20(and%20its%20associated%20configuration)%20to%20a%20Data%20Processor%20record.">
				<COLUMN Type="GroupID-0" 	 Name="DataBufferGroupID" 	 StorageName="DATA_BUFFER_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="ProcessorUID" 	 StorageName="PROCESSOR_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="ProcessorType" 	 StorageName="PROCESSOR_TYPE" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,Producer,Consumer"/>
				<COLUMN Type="FixedChoiceData" 	 Name="ProcessorPluginName" 	 StorageName="PROCESSOR_PLUGIN_NAME" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,UDPDataListenerProducer,UDPDataListenerProducer,RawDataSaverConsumer,UDPDataStreamerConsumer,DemoDQMHistosConsumer"/>
				<COLUMN Type="ChildLink-0" 	 Name="LinkToProcessorConfiguration" 	 StorageName="LINK_TO_PROCESSOR_CONFIGURATION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLinkUID-0" 	 Name="LinkToProcessorUID" 	 StorageName="LINK_TO_PROCESSOR_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/DataDCS/TableInfo/MainSupervisorConfiguration.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
 <ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
   <CONFIGURATION Name="XDAQContextConfiguration">    
     <VIEW Name="XDAQ_CONTEXT_CONFIGURATION" Type="File,Database,DatabaseTest">
       <COLUMN Name="_UID"        		 		StorageName="_UID"             				DataType="VARCHAR2"/>
       <COLUMN Name="Security"           		StorageName="SECURITY"             				DataType="VARCHAR2"/>
       <COLUMN Type="Comment" 	Name="Comment"		        StorageName="COMMENT"  	           	DataType="VARCHAR2"/>
       <COLUMN Type="Author" 	Name="Author"		        StorageName="AUTHOR"  	           	DataType="VARCHAR2"		/>
       <COLUMN Type="Timestamp" 	Name="RecordInsertionTime"  StorageName="RECORD_INSERTION_TIME" DataType="TIMESTAMP WITH TIMEZONE"/>
     </VIEW>
   </CONFIGURATION>
 </ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/TheSupervisorConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
  <CONFIGURATION Name="TheSupervisorConfiguration">
    <VIEW Name="THE_SUPERVISOR_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
      <COLUMN Type="UID" 	                Name="SupervisorUID" 	                 StorageName="SUPERVISOR_UID" 		                   DataType="VARCHAR2" 		            DataChoices=""/>
      <COLUMN Type="ChildLink-FSM" 	      Name="LinkToStateMachineConfiguration" StorageName="LINK_TO_STATE_MACHINE_CONFIGURATION" 	 DataType="VARCHAR2" 		            DataChoices=""/>
      <COLUMN Type="ChildLinkGroupID-FSM" Name="StateMachineGroupID" 	           StorageName="STATE_MACHINE_GROUP_ID" 		           DataType="VARCHAR2" 		            DataChoices=""/>
      <COLUMN Type="YesNo" 	              Name="EnableStateChangesOverUDP" 	     StorageName="ENABLE_STATE_CHANGES_OVER_UDP" 		     DataType="VARCHAR2" 		            DataChoices=""/>
      <COLUMN Type="Data" 	              Name="IPAddressForStateChangesOverUDP" StorageName="IP_ADDRESS_FOR_STATE_CHANGES_OVER_UDP" DataType="VARCHAR2" 		            DataChoices=""/>
      <COLUMN Type="Data" 	              Name="PortForStateChangesOverUDP" 	   StorageName="PORT_FOR_STATE_CHANGES_OVER_UDP" 		   DataType="NUMBER" 		              DataChoices=""/>
      <COLUMN Type="YesNo" 	              Name="EnableAckForStateChangesOverUDP" StorageName="ENABLE_ACK_FOR_STATE_CHANGES_OVER_UDP" DataType="VARCHAR2" 		            DataChoices=""/>
      <COLUMN Type="YesNo"                Name="EnableARTDAQCommanderPlugin"     StorageName="ENABLE_ARTDAQ_COMMANDER_PLUGIN"        DataType="VARCHAR2"                DataChoices=""/>
      <COLUMN Type="Data" 	              Name="ARTDAQCommanderType" 	           StorageName="ARTDAQ_COMMANDER_PLUGIN_TYPE" 		     DataType="VARCHAR2" 		            DataChoices=""/>
      <COLUMN Type="Data" 	              Name="ARTDAQCommanderID" 	             StorageName="ARTDAQ_COMMANDER_ID" 		               DataType="NUMBER" 		              DataChoices=""/>
      <COLUMN Type="Comment" 	            Name="CommentDescription" 	           StorageName="COMMENT_DESCRIPTION" 		               DataType="VARCHAR2"            		DataChoices=""/>
      <COLUMN Type="Author" 	            Name="Author" 	                       StorageName="AUTHOR" 		                           DataType="VARCHAR2" 		            DataChoices=""/>
      <COLUMN Type="Timestamp" 	          Name="RecordInsertionTime" 	           StorageName="RECORD_INSERTION_TIME" 		             DataType="TIMESTAMP WITH TIMEZONE" DataChoices=""/>
    </VIEW>
  </CONFIGURATION>
</ROOT>

=== Mu2e/otsdaq_mu2e/Data/ConfigurationInfo.updateots.bk/FESlowControlsConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="FESlowControlsConfiguration">
			<VIEW Name="FE_SLOW_CONTROLS_CONFIGURATION" Type="File,Database,DatabaseTest">
				<COLUMN Type="GroupID-SlowControlChannels" 	 Name="FEGroupID" 	 StorageName="FE_GROUP_ID" 		DataType="VARCHAR2"/>
				<COLUMN Type="UID" 	 Name="ChannelName" 	 StorageName="CHANNEL_NAME" 		DataType="VARCHAR2"/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="ChannelDataType" 	 StorageName="CHANNEL_DATA_TYPE" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="UniversalInterfaceAddress" 	 StorageName="UNIVERSAL_INTERFACE_ADDRESS" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="UniversalDataBitOffset" 	 StorageName="UNIVERSAL_DATA_BIT_OFFSET" 		DataType="NUMBER"/>
				<COLUMN Type="YesNo" 	 Name="ReadAccess" 	 StorageName="READ_ACCESS" 		DataType="VARCHAR2"/>
				<COLUMN Type="YesNo" 	 Name="WriteAccess" 	 StorageName="WRITE_ACCESS" 		DataType="VARCHAR2"/>
				<COLUMN Type="TrueFalse" 	 Name="RecordChangesOnly" 	 StorageName="RECORD_CHANGES_ONLY" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="DelayBetweenSamplesInSeconds" 	 StorageName="DELAY_BETWEEN_SAMPLES_IN_SECONDS" 		DataType="NUMBER"/>
				<COLUMN Type="YesNo" 	 Name="MonitoringEnabled" 	 StorageName="MONITORING_ENABLED" 		DataType="VARCHAR2"/>
				<COLUMN Type="YesNo" 	 Name="LocalSavingEnabled" 	 StorageName="LOCAL_SAVING_ENABLED" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="LocalFilePath" 	 StorageName="LOCAL_FILE_PATH" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="RadixFileName" 	 StorageName="RADIX_FILE_NAME" 		DataType="VARCHAR2"/>
				<COLUMN Type="TrueFalse" 	 Name="SaveBinaryFile" 	 StorageName="SAVE_BINARY_FILE" 		DataType="VARCHAR2"/>
				<COLUMN Type="YesNo" 	 Name="AlarmsEnabled" 	 StorageName="ALARMS_ENABLED" 		DataType="VARCHAR2"/>
				<COLUMN Type="TrueFalse" 	 Name="LatchAlarms" 	 StorageName="LATCH_ALARMS" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="LowLowThreshold" 	 StorageName="LOW_LOW_THRESHOLD" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="LowThreshold" 	 StorageName="LOW_THRESHOLD" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="HighThreshold" 	 StorageName="HIGH_THRESHOLD" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="HighHighThreshold" 	 StorageName="HIGH_HIGH_THRESHOLD" 		DataType="VARCHAR2"/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2"/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2"/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE"/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/FESupervisorConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="FESupervisorConfiguration">
			<VIEW Name="FE_SUPERVISOR_CONFIGURATION" Type="File,Database,DatabaseTest">
				<COLUMN Type="UID" 	 Name="SupervisorUID" 	 StorageName="SUPERVISOR_UID" 		DataType="VARCHAR2"/>
				<COLUMN Type="ChildLink-0" 	 Name="LinkToFEInterfaceConfiguration" 	 StorageName="LINK_TO_FE_INTERFACE_CONFIGURATION" 		DataType="VARCHAR2"/>
				<COLUMN Type="ChildLinkGroupID-0" 	 Name="LinkToFEInterfaceGroupID" 	 StorageName="LINK_TO_FE_INTERFACE_GROUP_ID" 		DataType="VARCHAR2"/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2"/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2"/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE"/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/FEInterfaceConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="FEInterfaceConfiguration">
			<VIEW Name="FE_INTERFACE_CONFIGURATION" Type="File,Database,DatabaseTest" Description="This%20table%20is%20used%20to%20associate%20a%20plugin%20class%20(and%20its%20configuration%20specifics)%20with%20a%20front-end%20device.%0A%0AThis%20table%20can%20be%20optionally%20used%20to%20associate%20a%20slow%20control%20configuration%20with%20a%20front-end.">
				<COLUMN Type="GroupID-0" 	 Name="FEInterfaceGroupID" 	 StorageName="FE_INTERFACE_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="FEInterfaceUID" 	 StorageName="FE_INTERFACE_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="FEInterfacePluginName" 	 StorageName="FE_INTERFACE_PLUGIN_NAME" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,CFOFrontEndInterface,DTCFrontEndInterface,CAPTANSignalGenerator"/>
				<COLUMN Type="ChildLink-0" 	 Name="LinkToFETypeConfiguration" 	 StorageName="LINK_TO_FE_TYPE_CONFIGURATION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLinkUID-0" 	 Name="LinkToFETypeUID" 	 StorageName="LINK_TO_FE_TYPE_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLink-SlowControlChannels" 	 Name="LinkToSlowControlChannelsConfiguration" 	 StorageName="LINK_TO_SLOW_CONTROL_CHANNELS_CONFIGURATION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLinkGroupID-SlowControlChannels" 	 Name="LinkToSlowControlChannelsGroupID" 	 StorageName="LINK_TO_SLOW_CONTROL_CHANNELS_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLink-SlowControlsMonitor" 	 Name="LinkToSlowControlsMonitorConfiguration" 	 StorageName="LINK_TO_SLOW_CONTROLS_MONITOR_CONFIGURATION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLinkUID-SlowControlsMonitor" 	 Name="LinkToSlowControlsMonitorUID" 	 StorageName="LINK_TO_SLOW_CONTROLS_MONITOR_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="SlowControlsTxSocketIPAddress" 	 StorageName="SLOW_CONTROLS_TX_SOCKET_IP_ADDRESS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="SlowControlsTxSocketPort" 	 StorageName="SLOW_CONTROLS_TX_SOCKET_PORT" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="YesNo" 	 Name="SlowControlsLocalAggregateSavingEnabled" 	 StorageName="SLOW_CONTROLS_LOCAL_AGGREGATE_SAVING_ENABLED" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="SlowControlsLocalFilePath" 	 StorageName="SLOW_CONTROLS_LOCAL_FILE_PATH" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="SlowControlsRadixFileName" 	 StorageName="SLOW_CONTROLS_RADIX_FILE_NAME" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="SlowControlsSaveBinaryFile" 	 StorageName="SLOW_CONTROLS_SAVE_BINARY_FILE" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/DataDCS/TableInfo/IterationCommandExecuteFEMacroTableInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
        <ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
                <CONFIGURATION Name="IterationCommandExecuteFEMacroConfiguration">
                        <VIEW Name="ITERATION_COMMAND_EXECUTE_FE_MACRO_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
                                <COLUMN Type="UID"          Name="CommandID"          StorageName="COMMAND_ID"                 DataType="VARCHAR2"                 DataChoices=""/>
                                <COLUMN Type="ChildLink-targets"          Name="LinkToTargets"          StorageName="LINK_TO_TARGETS"                 DataType="VARCHAR2"                 DataChoices="arbitraryBool=0,IterationTargetConfiguration"/>
                                <COLUMN Type="ChildLinkGroupID-targets"          Name="LinkToTargetsGroupID"          StorageName="LINK_TO_TARGETS_GROUP_ID"                 DataType="VARCHAR2"                 DataChoices=""/>
                                <COLUMN Type="Data"          Name="MacroName"          StorageName="MACRO_NAME"                 DataType="VARCHAR2"                 DataChoices=""/>
                                <COLUMN Type="ChildLink-macroDimensionalLoops"          Name="LinkToMacroDimensionalLoopTable"          StorageName="LINK_TO_MACRO_DIMENSIONAL_LOOP_TABLE"                 DataType="VARCHAR2"                 DataChoices="arbitraryBool=0,NO_LINK,IterationCommandMacroDimensionalLoopConfiguration"/>
                                <COLUMN Type="ChildLinkGroupID-macroDimensionalLoops"          Name="LinkToMacroDimensionalLoopGroupID"          StorageName="LINK_TO_MACRO_DIMENSIONAL_LOOP_GROUP_ID"                 DataType="VARCHAR2"                 DataChoices=""/>
                                <COLUMN Type="YesNo"          Name="EnableSavingOutputsToFile"          StorageName="ENABLE_SAVING_OUTPUTS_TO_FILE"                 DataType="VARCHAR2"                 DataChoices=""/>
                                <COLUMN Type="Data"          Name="OutputFilePath"          StorageName="OUTPUT_FILE_PATH"                 DataType="VARCHAR2"                 DataChoices=""/>
                                <COLUMN Type="Data"          Name="OutputFileRadix"          StorageName="OUTPUT_FILE_RADIX"                 DataType="VARCHAR2"                 DataChoices=""/>
                                <COLUMN Type="Comment"          Name="CommentDescription"          StorageName="COMMENT_DESCRIPTION"                 DataType="VARCHAR2"                 DataChoices=""/>
                                <COLUMN Type="Author"          Name="Author"          StorageName="AUTHOR"                 DataType="VARCHAR2"                 DataChoices=""/>
                                <COLUMN Type="Timestamp"          Name="RecordInsertionTime"          StorageName="RECORD_INSERTION_TIME"                 DataType="TIMESTAMP WITH TIMEZONE"                 DataChoices=""/>
                        </VIEW>
                </CONFIGURATION>
        </ROOT>
