=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo/ConfigurationInfo.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ROOT">
	<xs:complexType>
  	<xs:sequence>
		<xs:element name="CONFIGURATION">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="VIEW" minOccurs="1" maxOccurs="1">
			<xs:complexType>
				<xs:sequence>
				<xs:element name="COLUMN" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="Type"	     type="xs:string" />
					<xs:attribute name="Name"	     type="xs:string" />
					<xs:attribute name="StorageName" type="xs:string" />
					<xs:attribute name="DataType"	 type="xs:string" />
					<xs:attribute name="DataChoices" type="xs:string" />
				</xs:complexType>
				</xs:element>
				</xs:sequence>
				<xs:attribute name="Name" 			type="xs:string"/>
				<xs:attribute name="Type" 			type="xs:string"/>
				<xs:attribute name="Description" 	type="xs:string"/>
			</xs:complexType>
			</xs:element>
			</xs:sequence>
			<xs:attribute name="Name" 			type="xs:string"/>
		</xs:complexType>
		</xs:element>
	</xs:sequence>
	</xs:complexType>
	</xs:element>
</xs:schema>

=== Mu2e/otsdaq_mu2e/Data/ConfigurationInfo.updateots.bk/IterateConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="IterateConfiguration">
			<VIEW Name="ITERATE_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="IterationPlanName" 	 StorageName="ITERATION_PLAN_NAME" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLink-iterationPlan" 	 Name="LinkToIterationPlanTable" 	 StorageName="LINK_TO_ITERATION_PLAN_TABLE" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,IterationPlanConfiguration"/>
				<COLUMN Type="ChildLinkGroupID-iterationPlan" 	 Name="LinkToIterationPlanGroupID" 	 StorageName="LINK_TO_ITERATION_PLAN_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data/ConfigurationInfo.updateots.bk/IterationTargetConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="IterationTargetConfiguration">
			<VIEW Name="ITERATION_TARGET_CONFIGURATION" Type="File,Database,DatabaseTest" Description="This%20table%20forms%20groups%20of%20targets%20for%20the%20iterator.%20A%20group%20can%20span%20multiple%20front-end%20interfaces%20or%20whatever%20(as%20long%20as%20they%20have%20the%20iterator%20can%20modify%20the%20same%20relative%20path%20field).">
				<COLUMN Type="GroupID-targets" 	 Name="IterationTargetGroupID" 	 StorageName="ITERATION_TARGET_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="IterationTargetGroupMemberUID" 	 StorageName="ITERATION_TARGET_GROUP_MEMBER_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLink-target" 	 Name="LinkToTarget" 	 StorageName="LINK_TO_TARGET" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1"/>
				<COLUMN Type="ChildLinkUID-target" 	 Name="LinkToTargetUID" 	 StorageName="LINK_TO_TARGET_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data/ConfigurationInfo/DTCInterfaceConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="DTCInterfaceConfiguration">
			<VIEW Name="DTC_INTERFACE_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="EmulatorMode" 	 StorageName="EMULATOR_MODE" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="LocationInChain" 	 StorageName="LOCATION_IN_CHAIN" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="DeviceIndex" 	 StorageName="DEVICE_INDEX" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="ConfigureClock" 	 StorageName="CONFIGURE_CLOCK" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="ChildLink-ROC" 	 Name="LinkToROCGroupTable" 	 StorageName="LINK_TO_ROC_GROUP_TABLE" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,ROCInterfaceConfiguration,NO_LINK"/>
				<COLUMN Type="ChildLinkGroupID-ROC" 	 Name="LinkToROCGroupID" 	 StorageName="LINK_TO_ROC_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data/ConfigurationInfo.updateots.bk/XDAQApplicationConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="XDAQApplicationConfiguration">
			<VIEW Name="XDAQ_APPLICATION_CONFIGURATION" Type="File,Database,DatabaseTest" Description="Each%20record%20in%20this%20table%20represents%20a%20XDAQ%20Application.%20A%20group%20of%20XDAQ%20Applications%20form%20a%20XDAQ%20Context.%20In%20otsdaq%2C%20XDAQ%20Applications%20are%20also%20referred%20to%20as%20%22supervisors%2C%22%20and%20each%20supervisor%20has%20some%20specialized%20role%20with%20names%20such%20as%20%22Gateway%20Supervisor%22%20or%20%22Chat%20Supervisor%22%20or%20%22Macro%20Maker%20Supervisor.%22%0A%0AHere%20are%20some%20notes%20on%20particular%20fields%3A%0A%0A%09-%20%3Cb%3EClass%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Class'%20field%20refers%20to%20a%20valid%20ots%20supervisor%20class.%20Suggested%20classes%20are%20provided%20in%20the%20drop-down%20(e.g.%20%22ots%3A%3ASupervisor%22)%2C%20however%20arbitrary%20editing%20is%20allowed.%0A%0ANote%20that%20%22ots%3A%3AFESupervisor%2C%22%20%22ots%3A%3ADataManagerSupervisor%2C%22%20and%20%22ots%3A%3AARTDAQDataManagerSupervisor%22%20all%20are%20defined%20in%20the%20same%20library%20so%20the%20'Module'%20path%20for%20these%20classes%20should%20be%20%22%24%7BOTSDAQ_LIB%7D%2FlibCoreSupervisors.so.%22%0A%3C%2FINDENT%3E%0A%09-%20%3Cb%3EId%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Id'%20field%20is%20the%20XDAQ%20Application%20ID.%20It%20must%20be%20unique%20within%20an%20application%20group%20(XDAQ%20Context)%20and%20is%20usually%20a%20value%20between%20200%20and%20999.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EInstance%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Instance'%20field%20is%20the%20XDAQ%20Application%20instance.%20The%20value%20is%20usually%201%2C%20however%20arbitrary%20editing%20is%20allowed.%3C%2FINDENT%3E%0A%09-%20%3Cb%3ENetwork%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Network'%20field%20is%20the%20XDAQ%20Application%20network.%20The%20value%20is%20usually%20%22local%2C%22%20however%20arbitrary%20editing%20is%20allowed.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EGroup%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Group'%20field%20is%20the%20XDAQ%20Application%20group.%20The%20value%20is%20usually%20%22daq%2C%22%20however%20arbitrary%20editing%20is%20allowed.%3C%2FINDENT%3E%0A%09-%20%3Cb%3EModule%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'Module'%20field%20refers%20to%20the%20path%20of%20the%20class%20library%20which%20corresponds%20to%20the%20selected%20ots%20supervisor%20class.%20Suggested%20library%20paths%20are%20provided%20in%20the%20drop-down%20(e.g.%20%22%24%7BOTSDAQ_LIB%7D%2FlibSupervisor.so%22)%2C%20however%20arbitrary%20editing%20is%20allowed.%0A%0ANote%20that%20%22ots%3A%3AFESupervisor%2C%22%20%22ots%3A%3ADataManagerSupervisor%2C%22%20and%20%22ots%3A%3AARTDAQDataManagerSupervisor%22%20all%20are%20defined%20in%20the%20same%20library%20so%20the%20'Module'%20path%20for%20these%20classes%20should%20be%20%22%24%7BOTSDAQ_LIB%7D%2FlibCoreSupervisors.so.%22%0A%3C%2FINDENT%3E%0A%09-%20%3Cb%3EConfigurePriority%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'ConfigurePriority'%20field%20sets%20the%20priority%2C%20among%20all%20other%20XDAQ%20Applications%2C%20of%20the%20Application%20when%20the%20%3Ci%3Eotsdaq%3C%2Fi%3E%20state%20machine%20is%20Configured.%20The%20priority%20value%20is%20from%201%20to%20255%20inclusive.%200%20(Default)%20is%20translated%20to%20a%20priority%20of%20100.%20%0A%0AFor%20example%2C%20if%20there%20are%20three%20applications%20A%2C%20B%2C%20C%20with%20priority%201%2C%2099%2C%200%20respectively...%20then%20A%20will%20be%20configured%20first%2C%20followed%20by%20C%2C%20and%20then%20B.%09%0A%3C%2FINDENT%3E%0A%09-%20%3Cb%3EStartPriority%2C%20StopPriority%3A%3C%2Fb%3E%0A%3CINDENT%3EThe%20'StartPriority'%20and%20'StopPriority'%20fields%20are%20the%20similar%20to%20the%20'ConfigurePriority'%20field%20except%20for%20they%20set%20the%20priority%20for%20the%20Start%20and%20Stop%20state%20machine%20transitions.%0A%3C%2FINDENT%3E">
				<COLUMN Type="GroupID-0" 	 Name="ApplicationGroupID" 	 StorageName="APPLICATION_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="ApplicationUID" 	 StorageName="APPLICATION_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLink-0" 	 Name="LinkToSupervisorTable" 	 StorageName="LINK_TO_SUPERVISOR_TABLE" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,NO_LINK,GatewaySupervisorConfiguration,FESupervisorConfiguration,FEDataManagerSupervisorConfiguration,DataManagerSupervisorConfiguration,ARTDAQAggregatorConfiguration,ARTDAQBuilderConfiguration,ECLSupervisorConfiguration"/>
				<COLUMN Type="ChildLinkUID-0" 	 Name="LinkToSupervisorUID" 	 StorageName="LINK_TO_SUPERVISOR_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="Class" 	 StorageName="CLASS" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,ots%3A%3AGatewaySupervisor,ots%3A%3AFESupervisor,ots%3A%3ADataManagerSupervisor,ots%3A%3AARTDAQDataManagerSupervisor,ots%3A%3AEventBuilderApp,ots%3A%3ADataLoggerApp,ots%3A%3AConfigurationGUISupervisor,ots%3A%3AMacroMakerSupervisor,ots%3A%3AVisualSupervisor,ots%3A%3AChatSupervisor,ots%3A%3AConsoleSupervisor,ots%3A%3ALogbookSupervisor,ots%3A%3AControlsDashboardSupervisor"/>
				<COLUMN Type="UniqueData" 	 Name="Id" 	 StorageName="ID" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="Instance" 	 StorageName="INSTANCE" 		DataType="NUMBER" 		DataChoices="arbitraryBool=1,1"/>
				<COLUMN Type="FixedChoiceData" 	 Name="Network" 	 StorageName="NETWORK" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,local"/>
				<COLUMN Type="FixedChoiceData" 	 Name="Group" 	 StorageName="GROUP" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,daq"/>
				<COLUMN Type="FixedChoiceData" 	 Name="Module" 	 StorageName="MODULE" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=1,%24%7BOTSDAQ_LIB%7D%2FlibSupervisor.so,%24%7BOTSDAQ_LIB%7D%2FlibCoreSupervisors.so,%24%7BOTSDAQ_LIB%7D%2FlibEventBuilderApp.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibChat.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibConsole.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibLogbook.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibVisualization.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibConfigurationGUI.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibControlsDashboard.so,%24%7BOTSDAQ_UTILITIES_LIB%7D%2FlibMacroMaker.so,%24%7BOTSDAQ_LIB%7D%2FlibDispatcherApp.so,%24%7BOTSDAQ_LIB%7D%2FlibDataLoggerApp.so"/>
				<COLUMN Type="Data" 	 Name="ConfigurePriority" 	 StorageName="CONFIGURE_PRIORITY" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="StartPriority" 	 StorageName="START_PRIORITY" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="StopPriority" 	 StorageName="STOP_PRIORITY" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="ChildLink-PropertyGroup" 	 Name="LinkToPropertyTable" 	 StorageName="LINK_TO_PROPERTY_TABLE" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,NO_LINK,XDAQApplicationPropertyConfiguration"/>
				<COLUMN Type="ChildLinkGroupID-PropertyGroup" 	 Name="LinkToPropertyGroupID" 	 StorageName="LINK_TO_PROPERTY_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data/ConfigurationInfo/MessageFacilityConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="MessageFacilityConfiguration">
			<VIEW Name="MESSAGE_FACILITY_CONFIGURATION" Type="File,Database,DatabaseTest">
				<COLUMN Type="UID" 	 Name="UID" 	 StorageName="UID" 		DataType="VARCHAR2"/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2"/>
				<COLUMN Type="TrueFalse" 	 Name="EnableUDPForwarding" 	 StorageName="ENABLE_UDP_FORWARDING" 		DataType="VARCHAR2"/>
				<COLUMN Type="YesNo" 	 Name="ForwardToWebConsoleGUI" 	 StorageName="FORWARD_TO_WEB_CONSOLE_GUI" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="WebConsoleForwardingIPAddress" 	 StorageName="WEB_CONSOLE_FORWARDING_IP_ADDRESS" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="WebConsoleForwardingPort0" 	 StorageName="WEB_CONSOLE_FORWARDING_PORT0" 		DataType="NUMBER"/>
				<COLUMN Type="Data" 	 Name="WebConsoleForwardingPort1" 	 StorageName="WEB_CONSOLE_FORWARDING_PORT1" 		DataType="NUMBER"/>
				<COLUMN Type="YesNo" 	 Name="ForwardToQTViewerGUI" 	 StorageName="FORWARD_TO_QT_VIEWER_GUI" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="QTViewerForwardingIPAddress" 	 StorageName="QT_VIEWER_FORWARDING_IP_ADDRESS" 		DataType="VARCHAR2"/>
				<COLUMN Type="Data" 	 Name="QTViewerForwardingPort" 	 StorageName="QT_VIEWER_FORWARDING_PORT" 		DataType="NUMBER"/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2"/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2"/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE"/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/IterationCommandModifyGroupConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="IterationCommandModifyGroupConfiguration">
			<VIEW Name="ITERATION_COMMAND_MODIFY_GROUP_CONFIGURATION" Type="File,Database,DatabaseTest" Description="'DoTrackGroupChanges'%20-%20when%20true%2C%20will%20save%20modifications%20that%20are%20configured%20in%20a%20new%20group.%20When%20false%2C%20modificaitons%20will%20be%20saved%20to%20a%20temporary%20group%20and%20will%20not%20be%20saved%20as%20new%20group%20keys%20and%20table%20versions%20in%20the%20configuration%20database.">
				<COLUMN Type="UID" 	 Name="CommandID" 	 StorageName="COMMAND_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLink-targets" 	 Name="LinkToTargets" 	 StorageName="LINK_TO_TARGETS" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,IterationTargetConfiguration"/>
				<COLUMN Type="ChildLinkGroupID-targets" 	 Name="LinkToTargetsGroupID" 	 StorageName="LINK_TO_TARGETS_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="TrueFalse" 	 Name="DoTrackGroupChanges" 	 StorageName="DO_TRACK_GROUP_CHANGES" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="RelativePathToField" 	 StorageName="RELATIVE_PATH_TO_FIELD" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="FieldStartValue" 	 StorageName="FIELD_START_VALUE" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="FieldIterationStepSize" 	 StorageName="FIELD_ITERATION_STEP_SIZE" 		DataType="NUMBER" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data_02/ConfigurationInfo.updateots.bk/IterationCommandBeginLabelConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="IterationCommandBeginLabelConfiguration">
			<VIEW Name="ITERATION_COMMAND_BEGIN_LABEL_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="UID" 	 Name="CommandID" 	 StorageName="COMMAND_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Data" 	 Name="Label" 	 StorageName="LABEL" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>

=== Mu2e/otsdaq_mu2e/Data/ConfigurationInfo.updateots.bk/IterationPlanConfigurationInfo.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
	<ROOT xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ConfigurationInfo.xsd">
		<CONFIGURATION Name="IterationPlanConfiguration">
			<VIEW Name="ITERATION_PLAN_CONFIGURATION" Type="File,Database,DatabaseTest" Description="No%20description.">
				<COLUMN Type="GroupID-iterationPlan" 	 Name="IterationPlanGroupID" 	 StorageName="ITERATION_PLAN_GROUP_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="UID" 	 Name="IterationPlanCommandID" 	 StorageName="ITERATION_PLAN_COMMAND_ID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="OnOff" 	 Name="Status" 	 StorageName="STATUS" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="FixedChoiceData" 	 Name="CommandType" 	 StorageName="COMMAND_TYPE" 		DataType="VARCHAR2" 		DataChoices="arbitraryBool=0,BEGIN_LABEL,REPEAT_LABEL,CHOOSE_FSM,CONFIGURE_ACTIVE_GROUP,CONFIGURE_ALIAS,CONFIGURE_GROUP,MODIFY_ACTIVE_GROUP,EXECUTE_MACRO,EXECUTE_FE_MACRO,RUN"/>
				<COLUMN Type="ChildLink-command" 	 Name="LinkToCommandTable" 	 StorageName="LINK_TO_COMMAND_TABLE" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="ChildLinkUID-command" 	 Name="LinkToCommandUID" 	 StorageName="LINK_TO_COMMAND_UID" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Comment" 	 Name="CommentDescription" 	 StorageName="COMMENT_DESCRIPTION" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Author" 	 Name="Author" 	 StorageName="AUTHOR" 		DataType="VARCHAR2" 		DataChoices=""/>
				<COLUMN Type="Timestamp" 	 Name="RecordInsertionTime" 	 StorageName="RECORD_INSERTION_TIME" 		DataType="TIMESTAMP WITH TIMEZONE" 		DataChoices=""/>
			</VIEW>
		</CONFIGURATION>
	</ROOT>
